### PR TITLE
Coop cutscenes

### PR DESCRIPTION
**Pull request by MexMeRcUrY**
enhancements discribed in #348

### CODE REVIEW

**Comment by Hendricks266** [comment]
The sdltheora library is unnecessary. You only need libtheora. Look at EDuke32's use of libvpx. Ideally both formats should be supported by the functionality you introduce.

>  Files changed 457
> +137,282

:/

**Comment by CommonLoon102** [comment]
Hi,

Wow, a lot of effort has been done! Nice!

Some things to consider:
- In blood.cpp, unnecessary whitespace changes at line 90, 626 and 1111.
- Use `Bstrcpy` instead of `strcpy`.
- Use `Bstrcat` instead of `strcat`.
- Use `Bstrlen` instead of `strlen`.
- Use `Bstrrchr` instead of `strrchr`.
- In `G_GetGameDir` there is some strange returns (`return("...")`).
- `G_GetGameDir` is a copy-pasta of `G_AddSearchPaths`, therefore it is duplicated code, it needs to be refactored.
- The video quality of the OGVs are terrible compared to the original. Therefore, if the user has both FS and OUWB installed, it should use the OUWB files instead. (I know that this is a draft and the order might have been changed for debugging reasons.)
- In `credits.cpp` change tabs back to spaces as it was before, because it is messing up the code comparison (there are other unnecessary whitespace changes too).
- Use `BMAX_PATH` instead of `MAX_PATH`.
- Use `BMAX_PATH` instead of `FILENAME_MAX`.
- For some reason when pressing escape when the cinametics are playing, the game will freeze for a few seconds and audio still plays for the video.
- In windowed mode when the credits or cinametics are playing there are two windows: an empty game window and a borderless window with the video playing in it. I can move the game window from behind the video window.
- In fullscreen mode the cinametics are stretched and not keeping the original aspect ratio if I'm playing in for example 640x480.
- In fullscreen mode the whole screen flickers every time when a video is about to play, I can see my other windows open in Windows for a very short period of time.
- `bool filefound` is an unused variable.
- In the menu it is somewhere called `cut-scenes`, somewhere else it is `cutscenes`.
- I don't think it is needed as a multiplayer setting, but currently the setting does nothing because it isn't synchronized between the players, it is not in gPacketStartGame.
- Need to test it on Linux at least, and test if it still compiles and runs with USE_OPENGL=0 and without SSE2, as I see libtheora adds some SSE2 requirements. It is not a problem if OGV video playback needs SSE2, but if somebody doesn't have the OGVs and doesn't have SSE2 either, the game should still work with the old videos

**Comment by MexMeRcUrY** [comment]
Thank you very much for the detailed  feedback. ill work on everything you pointed out and inproove

**Comment by Hendricks266** [comment]
>     * Use `Bstrcpy` instead of `strcpy`.
>     * Use `Bstrcat` instead of `strcat`.
>     * Use `Bstrlen` instead of `strlen`.
>     * Use `Bstrrchr` instead of `strrchr`.

Don't do these four. compat.h says: `DEPRECATED: Standard library prefixing`. We only use the prefix for a case like Bstrcasecmp where strcasecmp isn't always available, such as MSVC.

**Pull request closed without merging**
