### PR TITLE
Blood: Use kGameType/kGameFlag constants for nGameType/uGameFlags

### PR DESCRIPTION
**Pull request by tmyqlfpir**
This PR replaces the constant numbers with friendlier names for level struct nGameType/uGameFlags members.

### CODE REVIEW

**Comment by mjr4077au** [comment]
I'm sure many will appreciate the efforts spent here to document these magic constants. I look forward to implementing this in Raze for cross-port consistency. They also enhance the friendliness to external contributors since the code learning curve is reduced.

**Comment by tmyqlfpir** [comment]
Thanks, hopefully my PRs are not stepping on anyone's toes over in the Raze branch when it comes to documenting the many various unknown numbers.

**Comment by mjr4077au** [comment]
Definitely not stepping on our toes. The hardest part is transposing the documentation onto our source as we've changed so much from NBlood these days, but that's our problem 😅

**Comment by tmyqlfpir** [comment]
The refactoring/floatifying work done with Raze is admirable, and I hope that these PRs are helpful in some way. That said, commit https://github.com/nukeykt/NBlood/pull/651/commits/732150ae00b8b751bebac44f3f76241029672f3c does resolve this enhancement described here https://github.com/ZDoom/Raze/issues/671

**Pull request merged**
