### PR TITLE
Blood: Play Monolith and GTI intro logos

### PR DESCRIPTION
**Pull request by CommonLoon102**
Related issue: https://github.com/nukeykt/NBlood/issues/268

### CODE REVIEW

**Comment by CommonLoon102** [comment]
The flickering didn't occur to me, it was working fine. Then for some unknown reason it started to flicker when fading out. I restored this code from this PR where it didn't flicker for me, now this flickers too.

After the GTI.SMK has been played, the other in-game cinematics are broken: the lower half of the screen contains a still image about the last GTI.SMK frame.

I have no idea how to fix the GTI.SMK aspect ratio, even VLC gives back a different result compared to your screenshot.

I could solve your other bullets though, but not these three. I don't really care about these intro videos, they contain 0 value anyways. I'm closing this.

**Comment by Hendricks266** [comment]
Can you push what you have?

**Comment by sirlemonhead** [comment]
I can work on this if nobody else is interested.

**Comment by CommonLoon102** [comment]
OK, I found out the flickering happens when fading out from the sprite logo only when the renderer is OpenGL, it works with software rendering. The problem(?) is in `gSetDacRange`.

**Comment by CommonLoon102** [comment]
Using bool results in bad machine code. What could I say. C++ seems like a really mature language :D

**Comment by CommonLoon102** [comment]
In software mode the other issue is also absent: when the lower part of the GTI logo is shown when playing cinematics later (e.g. starting new game on episode 1).

**Comment by CommonLoon102** [comment]
Using the software renderer the title screen (gargolye with Blood and Plasma Pak) won't be visible if the SMKs were played.

**Comment by CommonLoon102** [comment]
@sirlemonhead this is as far as I go.

Remaining issues:
- The GTI.SMK's aspect ratio is not good for some reason
- If the GTI.SMK played at start then game cinematics won't play back correctly (but only in case of OpenGL)
- The fade out effect doesn't work in OpenGL (happening when the SMK files are not available)

**Comment by CommonLoon102** [comment]
Fixed in https://github.com/nukeykt/NBlood/commit/52ccfa68f60e65907e21cf0741f6fe0542279f08

**Pull request closed without merging**
