### PR TITLE
Fix tiny Calebs turning into large flameguys

### PR DESCRIPTION
**Pull request by CommonLoon102**
Related issue: https://github.com/nukeykt/NBlood/issues/108

This is just a cosmetic fix, doesn't affect gameplay.
The other code change where I fixed the AI state pointer also doesn't change anything since the structs have the same value.

### CODE REVIEW

**Comment by CommonLoon102** [comment]
When https://github.com/nukeykt/NBlood/commit/c5d28a2f09f7603956e2cb77fe17539fb0dbee55 gets merged into master, -4 needs to be changed to 64.

**Comment by nukeykt** [comment]
Their `BurnSearch` state are not the same though!

**Comment by CommonLoon102** [comment]
> 
> 
> Their `BurnSearch` state are not the same though!

How come? Sorry, I don't what you mean.

**Comment by nukeykt** [comment]
`AISTATE cultistBurnSearch = { kAiStateSearch, 3, -1, 3600, NULL, aiMoveForward, thinkSearch, &cultistBurnSearch };`
`AISTATE innocentBurnSearch = { kAiStateSearch, 3, -1, 3600, NULL, aiMoveForward, thinkSearch, NULL };`
Next state is differs

**Comment by CommonLoon102** [comment]
> 
> 
> `AISTATE cultistBurnSearch = { kAiStateSearch, 3, -1, 3600, NULL, aiMoveForward, thinkSearch, &cultistBurnSearch };`
> `AISTATE innocentBurnSearch = { kAiStateSearch, 3, -1, 3600, NULL, aiMoveForward, thinkSearch, NULL };`
> Next state is differs

OK, I'm blind :)

**Comment by nukeykt** [comment]
Wouldn't setting dude type to 252 be sufficient (which has proper x/yrepeat in SEQ files)?

**Comment by CommonLoon102** [comment]
> 
> 
> Wouldn't setting dude type to 252 be sufficient (which has proper x/yrepeat in SEQ files)?

If I set `pSprite->type = 252;` instead of scaling down the SEQ then they will behave differently, they will run around while flaming. If the type is 239 then they will stand still while flaming.

**Comment by CommonLoon102** [comment]
I have reverted every change which is not related to the size issue. By the way those changes didn't change any behavior, or I didn't notice.
I think you need to cherry pick the SEQ resizing change from mapedit branch before we want to merge this, so we won't forget to change -4 to 64 later.

For the behavior changes and issues, I've opened a separate issue, it is easier if we handle the size problem and the behavior problems separately because they are indeed a separate problem.
Maybe you decide that changing the behavior for flaming little Calebs and innocents are too huge gameplay changes for this mod, then we don't need to even start working on it and then I will close this issue: https://github.com/nukeykt/NBlood/issues/120

**Pull request merged**
