### PR TITLE
[Blood] Document unnamed sfx class variables

### PR DESCRIPTION
**Pull request by carnivoroussociety**
This PR names the remaining unnamed varaibles for the sfx class. It also includes fixes for flare sprites and shadows casting on room over room sectors, as well as fixing the lifeleech sprite.

### CODE REVIEW

**Comment by Hendricks266** [comment]
Thanks! Could you do an interactive rebase to squash commits that revise previous ones into the commit they revise?

**Comment by carnivoroussociety** [comment]
Sure, I've squashed the team fix into a single commit now. Is that what you meant?

**Comment by CommonLoon102** [comment]
A PR must fix only one thing not dozens of it. You need to open a separate PR for every single issue. Otherwise, don't be surprised if nobody reviews it and merges it.
Your contributions are really useful and it is good to see that someone is continuing this project, but to avoid regressions as much as possible, we need to follow the GitHub flow and do things in a structured way.

**Comment by carnivoroussociety** [comment]
Apologies - I'll separate this across multiple PRs at a later date.

**Comment by zZeck** [comment]
> Apologies - I'll separate this across multiple PRs at a later date.

I guess a later date has arrived!

This discussion is actually why I've been doing my stuff as a bunch of small PRs.

I'll try to look at your PRs tomorrow and point out anything I find, for whatever that'll be worth since I'm new to the codebase.

Thanks for doing all these fixes.

**Pull request closed without merging**
